### ISSUE TITLE
非常感谢作者的工作，有个问题想请教一下

### ISSUE THREAD

**Issue by ghostbreaken** [Giveupfree/SOTDrawRect#1]
在OTB100数据集上画图，只画了前8个数据的图，这是怎么回事呢？试了好几次都只有前8个的

**Comment by Giveupfree** [comment]
你好，我这里测试发现，如果电脑中途休眠了，则会意外中断，可以看一下报的什么错误么？

**Comment by ghostbreaken** [comment]
> 你好，我这里测试发现，如果电脑中途休眠了，则会意外中断，可以看一下报的什么错误么？

非常感谢你的回复，我这里电脑一直在运行，没有休眠，OTB100到第八个数据集就自动停了，也没有报错，代码我也没有修改，VOT2016倒是能画完，不知道到底哪里出了问题

**Comment by ghostbreaken** [comment]
老哥，能发下你的qq嘛？我加你，截个图你帮我看一下可以嘛？感激不尽

**Comment by Giveupfree** [comment]
qq:1845842896
